### ISSUE TITLE
Unable too see which ambulances are assigned to a given incident

### ISSUE THREAD

**Issue by s20462** [pjwstkIOprojekt/webclient#166]
Is there an option to see which ambulances are currently assigned to an incident?
is this a missing feature or it is expected behavior?

![image](https://user-images.githubusercontent.com/80460337/214207717-6420c2da-74d2-4d4c-b761-a117fa673881.png)

**Comment by s20967** [comment]
Thought it was unnecessary since in ambulance view you can see currently assigned incident.
