### ISSUE TITLE
Ofiara przytomna i nie oddycha

### ISSUE THREAD

**Issue by s18982** [pjwstkIOprojekt/webclient#33]
Funkcjonalność tworzenia zgłoszeń umożliwia przekazanie informacji, że poszkodowany nie oddycha i jednocześnie, że jest przytomny.
Powinniśmy wykluczyć taką sytuację. Formularz nie powinien przepuszczać tak zaznaczonych opcji zgłoszenia.

Ofiara nie może jednocześnie nie oddychać i być przytomną.
![Przechwytywanie](https://user-images.githubusercontent.com/61829917/167866296-ca60d6c1-c37d-4cb3-9826-6cb3eb79a2ba.JPG)

**Comment by s20967** [comment]
Suggested changes were implemented. New form prevents this issue from happening.
