### ISSUE TITLE
Kompilacja z problemami

### ISSUE THREAD

**Issue by s18982** [pjwstkIOprojekt/webclient#34]
Frontend uruchamia się, jednak z problemami (funkcjonuje bez problemów). Po załadowaniu się, dostaję za każdym razem komunikat, jak na grafice poniżej. 
![Przechwytywanie](https://user-images.githubusercontent.com/61829917/167868747-56b84379-1906-4d40-afaa-eaf724d1cf4c.JPG)

**Comment by s20967** [comment]
This issue is propably caused by incorrectly built dependencies. Deleting node_modules folder and rebuilding dependencies using `npm i` command should fix it. Make sure that `npm i` command executes properly before testing.
