### ISSUE TITLE
New notification issue

### ISSUE THREAD

**Issue by s18982** [pjwstkIOprojekt/webclient#55]
1) Search in the firt column (the kind of help) doesn't work. 
2) The idea of this table seems a little bit strange. Does the person reporting an accident have time to write justification for calling each of these services? Ordering the number of services also seems a little bit strange.
3) I know that I mentioned about it but I still claim that a person cannot be conscious unless he is breathing.

**Comment by s20967** [comment]
1. Those values are stored as numbers, so proper searching is impossible and would require custom implementation. I've disabled searching in this column for now.
2. Those were the requirements that we received, we jus realised them. This issue should be reported to analysis team instead.
3. This idea was publicly rejected during our classes. I don't know why you're bringing up this topic again.
